#!/bin/bash

gnome-terminal -e "python -m SimpleHTTPServer"

gnome-terminal -e "python Registry.py"

gnome-terminal -e "python Mapper.py"
gnome-terminal -e "python Mapper2.py"
gnome-terminal -e "python Mapper3.py"
gnome-terminal -e "python Mapper4.py"
gnome-terminal -e "python Mapper5.py"

gnome-terminal -e "python Reduce.py"

gnome-terminal -e "python Master.py"
